### ISSUE TITLE
neembu-rus.jar is missing in dist/lib

### ISSUE THREAD

**Issue by mardukbp** [shashaanktulsyan/spyfs#1]
In order to execute `java -jar spyfs.jar` [neembu-rus.jar](https://github.com/Neembuu-Uploader/neembuu-uploader/tree/master/modules/neembuu-rus) is necessary.

Thank you for sharing your method for deploying small JavaFX applications!

**Comment by nithyasharabheshwara** [comment]
Please try
https://github.com/shashaanktulsyan/spyfs/blob/master/neembuu-rus-1.0.jar

I made this era's ago. And the last time I tried I was not able to get SpyFs working. To be honest I didn't spend much time either. I am glad to see your interest in this. It was not at all a difficult thing to do when the first time I got it running. Those days I had a lot of time for hobby projects. Keep me posted regarding your progress in making this work, I will push the source code for `neembuu-rus` to GitHub and any other dependencies if it helps.  Ideally, I should have released all this to maven central, you are the first one asking, so until now such an opportunity did not come.

**Comment by mardukbp** [comment]
Thanks! SpyFs launches, but Pismo File Mount does not support the Linux kernel version in Ubuntu 20.04. I was thinking that FUSE could be an alternative.

Anyway, using `strace` I succeeded in collecting the necessary classes to create a custom JRE for a JavaFX app in Linux. The .zip file is 13 MB big because `libjvm.so` is twice as large as `libjvm.dll`. Thanks a lot for the inspiration and the details! I will try to shrink more JavaFX apps now :)
